#!/bin/bash
cd
mkdir projects
cd projects
echo "Install minimal startup packages by homebrew"
curl https://raw.githubusercontent.com/kiltum/dotfiles/master/brew.sh|bash
echo "Now grab other useful files"
git clone git@github.com:kiltum/dotfiles.git
cd dotfiles
./macos.sh
./bootstrap.sh
echo "Now please reboot and have a nice day"